name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: run the PR, not the push
    tags-ignore:
      - 'v*' #avoid rerun existing commit on release
  pull_request:

env:
  CI: true

jobs:
  lint:
    uses: NicTool/.github/.github/workflows/lint.yml@main

  coverage:
    uses: NicTool/.github/.github/workflows/coverage.yml@main
    secrets: inherit

  test:
    needs: lint
    uses: NicTool/.github/.github/workflows/test.yml@main
    secrets: inherit
